apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sparrow-storybook
  name: sparrow-storybook
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sparrow-storybook
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sparrow-storybook
    spec:
      containers:
        - image: sparrowprod.azurecr.io/sparrow-storybook:_BUILD__ID_
          name: sparrow-storybook
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 700Mi

          # livenessProbe:
          #   tcpSocket:
          #     port: 1422
          #   initialDelaySeconds: 15
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: sparrow-storybook
  labels:
    run: sparrow-storybook
spec:
  type: ClusterIP
  selector:
    app: sparrow-storybook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80